ApeWorX/ethpm-types

- ethpm_types/abi.py
- ethpm_types/contract_type.py
- ethpm_types/manifest.py
- pyproject.toml
- setup.py
- tests/test_examples.py
Updated pydantic models to work with Ape core.
Related issue: #
- refactor: `ABIType: name` and `ContractType: abi` to Optional so when calling dict they will not return empty keys
- refactor: `ContractType` properties to check for the existence of an`abi` list
- refactor: `pyproject.toml` to match updated repos
- refactor: `setup.py` for Beta and additional linting
- refactor: removed `GITHUB_ACCESSS_TOKEN` env var requirement, now optional
Ran test suite for this repo and core
> refactor: adjust pydantic  models

- ethpm_types/contract_type.py
Update `txns` back to match Ape core's `transactions`
Move over doc strings
fixes: #
> refactor: change txns to transactions and doc strings

- ethpm_types/base.py
Change 'indent' kwarg to 'separators' so the `.json()` method works correctly.
Noticed 'indent' was causing issues because of this default kwargument.
Realizing 'indent' needs to be None (which is the default: https://docs.python.org/3/library/json.html#json.dumps)
and we actually want separators here.
Thanks @fubuloubu for the help!
Can now output JSON from a PackageManifest e.g. `manifest_file_path.write_text(dependency_manifest.json())`
> fix: correct 'indent' kwarg to 'separators' in base json method

- ethpm_types/abi.py
- ethpm_types/contract_type.py
- setup.py
- tests/test_examples.py
Introduce more type safety into this library
[Discriminated Unions](https://pydantic-docs.helpmanual.io/usage/types/#discriminated-unions-aka-tagged-unions)
Tests pass... need to check with `ape`
> refactor: introduce unions via discriminated literal fields

- ethpm_types/base.py
- ethpm_types/contract_type.py
- setup.py
- tests/test_examples.py
fixes: #9
Add missing default flags to `.json()` method override
Added test case showing *exact* compliance of text data per EIP-2678 (important because a CID is computed based on the exact formatting)
> refactor: reduce complexity

- ethpm_types/abi.py
add `.signature` to all ABI types
> refactor: remove `.selector` from ABI types that don't need it

- tests/test_examples.py
see: https://github.com/ethpm/ethpm-spec/pull/174
Removes the temporary hack to ensure that examples did not fail due to errant newlines
> fix: no longer need to strip examples

- .pre-commit-config.yaml
- ethpm_types/abi.py
- pyproject.toml
- setup.py
- tests/test_cairo.py
Adds `StructABI` and `StructABIType` to handle essential Starknet contracts.
Copied existing ABI methodologies and schema from Starknet.
I added a test!
Question: Does this StructABI differ from Ethereum's?
> feat: structs

- ethpm_types/abi.py
Tuple and Struct `ABIType` variables have additional member `components` that is currently unprocessed but important for ABI decoding purposes.
> feat: add tuple components field to ABIType

- ethpm_types/contract_type.py
- ethpm_types/source.py
- ethpm_types/utils.py
- setup.py
- tests/test_corrupt_source.py
- tests/test_examples.py
- Change the `algorithm` into a str enum type
- Add support for sha3 and sha256 algos
- Change `Source.load_content` and `Source.compute_checksum` mutating methods on `Source` to instead be pure functions derived from the information in `Source`
NOTE: This is a breaking change, and will require using the `Source` class slightly differently, including updating it with a new version of itself if you wish to store files in a different way than it may have originally specified. Also note that the content will still fetch itself when requested, but it is not no longer being updated in `Source` object (see previous note)
- Fix a bug with hash type sizes in BIP122 URI
- Added a property to verify checksum correctness
- Add a `Hex` type to further validate hex-encoded strings for addresses, …
> refactor!: checksum operations into pure functions

- setup.py
the public methods did not change in version 1 range to 2 range, and we are preparing to upgrade eth-dependencies in ape so we need this loosened first.
> chore: support eth-utils 2.0 range

- ethpm_types/abi.py
Disallowed mutation of `ABIType`, there is no reason to modify it after instantiation.
> feat: disallow mutation of abi type

- ethpm_types/__init__.py
- ethpm_types/base.py
- ethpm_types/utils.py
- tests/test_hexbytes.py
Whenever you wanted to use HexBytes as a type with a pydantic model you would get a validation error, now HexBytes can be validated and serialized on a pydantic model.
fixes: #20 
Used the HexBytes class as a BaseModel, adding pydantic validation models
Used the Pydantic BaseModel class but specialized the `_get_value()` method to return `hex` when serializing.
> feat: hexbytes validation w/ pydantic

- ethpm_types/contract_type.py
- setup.py
- tests/test_solidity_and_vyper.py
Added selection of method and event ABIs from lists returned by `mutable_methods`, `view_methods` and `events` by name, selector and keccak of selector.
Subclassed list and overriden `__getitem__`
```python
selector = keccak(text='approve(address,uint256)')[:4]
contract_type.view_methods['balanceOf']
contract_type.mutable_methods['transfer']  # note: name may be ambiguous
contract_type.mutable_methods['approve(address,uint256)']
contract_type.mutable_methods[selector]
contract_type.mutable_methods[tx.data]
topic = keccak(text='Transfer(address,address,uint256)')
contract_type.events['Transfer']  # event names are not ambiguous
contract_type.events['Approval(address,address,uint256)']
contract_type.events[topic]
```
> feat: select methods and events by name, signature and keccak

- ethpm_types/abi.py
- ethpm_types/contract_type.py
- tests/test_examples.py
This allows ABIs to be able to reference other parts of their ABIs if needed, such as Cairo lang structs types used in Methods.
The contact types are optional so that you can still attempt to use ABIs without coming from a parsed `ContractType` class.
* Add excluded fields to the models representing optional contract type back-refs
* Set the contract types values when getting from contract type class
> feat: add contract type back references to the ABI classes

- ethpm_types/abi.py
- tests/test_solidity_and_vyper.py
Ignores the `contract_type` back reference for ABI classes
`repr=False`
> feat: ignore contract type in repr for ABI

- setup.py
While working on evm-trace, I installed ethpm-types and got an error running tests. The requests library isn't installed as part of this package, even though it used throughout.
> chore: add requests install

- .github/workflows/publish.yaml
- .pre-commit-config.yaml
- setup.py
Aligns settings but also a PR to generate a new release and figure out why 0.3.6 is unreachable.
> chore: bump settings sync with ape

- ethpm_types/source.py
- tests/test_corrupt_source.py
Allow `Source.content` to be `""`, and only disallow `None`
fixes: #48
Change content checks to check for `None`. If we happen to read in a source file that's empty, it's still a valid file but won't have content. Previously the conditional would cause it to fail and, since the source did not also have `urls`, would result in a `ValueError`
A test project with at least one empty source should be testable, and not throw the `ValueError` about missing content
> fix: allow empty-string content

- ethpm_types/contract_type.py
- tests/test_pc_map.py
Looks like I'm going to need this for the reverts work
We have `sourcemap` but that's for the AST specifically, and it's much easier to query `pc_pos_map[trace_frame.pc]`
Open to suggestions for the field naming and documentation!
> feat: add ContractType.pcmap

- ethpm_types/contract_type.py
The type of pcmap was accidentally leftover as `Optional[Dict[str, List[PCMapItem]]]` when it should just be `Optional[PCMap]`
> fix: pcmap type declaration

- ethpm_types/abi.py
- tests/test_abi.py
Some how did not realize this. UGH!
> fix: make `selector` a property on `ConstructorABI`

- .pre-commit-config.yaml
- docs/conf.py
- ethpm_types/manifest.py
- ethpm_types/source.py
- ethpm_types/utils.py
- setup.py
- tests/test_package_manifest.py
For some reaosn, `FileUrl` format fails pydantic validation for `AnyUrl`
Simple example:
```python
from pydantic import FileUrl, AnyUrl, BaseModel
from typing import Union
class GenericModel(BaseModel):
v: AnyUrl  # Failure case 
class FileModel(BaseModel):
v: FileUrl
class DontCareModel(BaseModel):
v: Union[AnyUrl, FileUrl]
value = 'file:///foo/bar'
try:
GenericModel(v=value)  # Fails
except Exception as err:
print(err)
model = FileModel(v=value)
assert model.v == value
test_model = DontCareModel(v=value)
assert model.v == value
print("success!")
```
Redefine as `AnyUrl = Union[_AnyUrl, FileUrl]`
Can now have file URL in manifest. See tests.
> fix: issue where could not use FileUrl in a manifest

- ethpm_types/contract_type.py
- tests/test_contract_type.py
This would simplify some things in the Ape framework.
Need a way to search for any method, whether it is mutable or view, in one spot.
This is useful for building up reports about methods, such as traces or gas reports.
Add `methods` property that iterated through both but it was an `ABIList` so you could do `contract_type.methods[selector]`.
See tests, as always.
It is highly enumerated there.
> feat: add method that gets method

- ethpm_types/base.py
- ethpm_types/contract_type.py
- setup.py
- tests/test_source_map.py
My main goal here is trying to understand, so if you review this PR, please make help me do so!
So I noticed that `__repr__` for `SourceMap` looked funny, so I starting poking in that. I found `SourceMapItem` and the `parse()` method so wanted to know more about how that worked because the docs were sort of missing.
* Adds `__repr__` implementation to `SourceMap`
* Adds `__str__` implementation to `SourceMap`
* Adds docs to `SourceMapItem`
* Renames `stop` to `length` in `SourceMapItem`
fixes: APE-581
> feat!: `sourcemap` repr, str, docs and fixes

- ethpm_types/ast.py
- tests/test_ast.py
Realized it would be convenient for coverage work to let us look up defining method AST nodes via found statement nodes.
The functions at module level AST are found via `[n for n in self.children if n.ast_type == "FunctionDef"]`
And if any function node contains the given line numbers, than it must be the defining function node.
Else it may not be in a function, and that is fine also.
> feat: able to get defining function in AST object [APE-677]

- ethpm_types/ast.py
- tests/test_ast.py
Hack that allows sending lists for to `Tuple[int, int, int, int]`.
Makes some things easier down the line.
> feat: allow list for tuple of line numbers [APE-679]

- ethpm_types/contract_type.py
- setup.py
noticed we were not using our own hexbytes class for contract bytescode.
seems like we can? shouldnt be a breaking change since the classes are supposed to be the same, unless it breaks someone `isinstance` check ... hmmmm.
> refactor: use our own hexbytes [APE-730]

- .pre-commit-config.yaml
- ethpm_types/ast.py
now, compiler APIs in Ape can add classify the ast nodes they create such that downstream services can use those classifications to parse content, such as knowing the nodes in a function def versus the function content (something we have to do for coverage)
* add new model
* add member to ast node
* default to unclassified, so it wont be breaking change
> feat: add a way to "classify" AST nodes [APE-755]

- ethpm_types/contract_type.py
- tests/data/SolidityContract.json
- tests/test_contract_type.py
This allows easier integrations with custom exceptions in downstream services, such as Ape.
Now, we can check for selectors to find the correct ABI.
* new abi list for errors
* refactored to save code
* added test
`contract_type.errors` should contains your custom solidity errors.
"0x123" in contract_type.errors to check for a selector
> feat: add `errors` calculated property on `ContractType` [APE-810]

- ethpm_types/ast.py
- tests/test_ast.py
When comparing ASTs / getting nodes (used in PCMap building in `ape-vyper`), if the length is 0 and the other is None, it really is the same thing .However, the comparison would fail and we would fail to find the source and it would cause all sorts of problems...
> fix: issue with no-length AST nodes [APE-908]

- ethpm_types/source.py
For better tracking of statements executed, it is kinda needed to include the pc value, especially when dealing with virtual statements. sorry, this was the way to go, a little forgotten but no biggie
> feat: pc property on statements [APE-956]

- ethpm_types/ast.py
- tests/test_ast.py
Now, the ASTNode object can also parse Solidity AST nodes.
* Allow secondary key of `nodeType`, which is like an alias for `ast_type`.
* Default line numbers to -1, this means `ape-solidity` will have to figure those out separately and set them (once we get there)
turn on AST when compiling in `ape-solidity` or tbd.
or try to parse some more complex ASTs
> feat: able to parse solidity AST objects [APE-966]

- ethpm_types/ast.py
- ethpm_types/source.py
- tests/test_ast.py
- tests/test_hexbytes.py
- tests/test_source.py
didn't realize sometimes AST nodes had names, which is useful for function definitions.
> feat: utilize AST name [APE-1014]

- ethpm_types/manifest.py
prevents grabbing sources from dict every  time
> perf: check sources once [APE-1100]

- ethpm_types/contract_type.py
- tests/test_contract_type.py
allow initializing contract type bytecode values using non-dicts. Sometimes it feels tedious to wrap bytecode in a dict like `{"bytecode": _bytes}`, especially when using Contract Types outside of ape compilers. This makes it a little easier.
A pydantic validator (`pre=True`)
`ContractContainer(abi=[], deploymentBytecode=HexBytes("0x123")`
> feat: allow initializing bytecodes using bytes [APE-1131]

- ethpm_types/__init__.py
- tests/test_package_manifest.py
Made sure that back refs were updating properly
fixes: #83
Thanks to https://stackoverflow.com/questions/63420889/fastapi-pydantic-circular-references-in-separate-files
New test passes
~~- [ ] Documentation has been updated~~
> fix: update forward refs [APE-1288]

- ethpm_types/manifest.py
- tests/conftest.py
- tests/test_package_manifest.py
since `__getattr__` was the only way to access a contract type nicely, it would causes issues when trying use one named `.meta`. Also fixes a strange thing that sometimes happens with attributes. Adds a couple tests
> fix: issue where could not access contract types with same name as attribute [APE-1379]

- ethpm_types/_pydantic_v1.py
- ethpm_types/abi.py
- ethpm_types/ast.py
- ethpm_types/base.py
- ethpm_types/contract_type.py
- ethpm_types/manifest.py
- ethpm_types/source.py
- ethpm_types/sourcemap.py
- ethpm_types/utils.py
- pyproject.toml
- setup.cfg
- setup.py
- tests/test_hexbytes.py
- tests/test_package_manifest.py
- tests/test_schema_fuzzing.py
- tests/test_source.py
support pydantic 2 in a backwards-compatible way.
try to import from `pydantic.v1` (works in v2) and fall back to `pydantic` (works in v1)
relax the dependency so it matches both v1 and v2.
this is a quick solution that allows us to keep compat with other packages that are starting to update to pydantic v2 already.
the full migration will require a more involved refactor.
> feat: support pydantic v2 [APE-1372]

- ethpm_types/manifest.py
- tests/test_package_manifest.py
As I am fixing something with dependencies in Ape, this will help simplify a thing.
a new method that unpacks the source content into the given destination path
see my test, I think it is clear.
> feat: add `unpack_sources()` method to package manifest [APE-1382]

- .pre-commit-config.yaml
- ethpm_types/manifest.py
- setup.cfg
- setup.py
- tests/test_package_manifest.py
fixes: #89 
Fixes: APE-1408
< => <=
make a package manifest with a project name containing every valid letter and number at least once.
> fix: package name couldn't contain all valid characters [APE-1408]

- ethpm_types/contract_type.py
- tests/test_contract_type.py
The latest merge to main in Ape core failed because of this bug!
So we need this patch released and then im going to pin to the next version in core.
handle empty dicts
core tests pass again
> fix: handle empty dict bytecodes [APE-1452]

- ethpm_types/manifest.py
- ethpm_types/source.py
- tests/test_package_manifest.py
- tests/test_source.py
* Adds method for getting a contract type's Compiler
* Adds method for updating a manifest's compilers list
* Adds equality override in Compiler for ignoring contractTypes in equality check.
* Fixes bug where we could not have None contract types even though it said we could
> feat: PackageManifest utilities for working with Compilers list [APE-1497]

- setup.py
Removed pysha3 from test dependencies.  Package is long deprecated and was causing a blocking compilation error on my local.  Does not appear to be used anywhere and appears to have no impact.
Deleted a line
Install and run tests
> fix: remove pysha3 from test dependencies

- ethpm_types/source.py
- ethpm_types/utils.py
- tests/test_source.py
`__eq__` and `__hash__` in `Compiler` did not account for settings.
This is actually really important in `ape-vyper` right now, as it groups input selections based on optimization pragmas.
first stringify  settings dict in a sorted consistent way _without_ `outputSelection` in it. Now, only compiler settings like evmVersion or optimization settings affect the str.
then place that str in the hash
when using `ape-vyper` 's 0.7 PR you can compile a contract with opimization pragma and it gets own Compiler entry separate from the others using the same version..
See test updates on this PR for a simpler example lol.
> fix: compilers with different settings were not disinguished

- ethpm_types/contract_type.py
- tests/test_contract_type.py
Added props to ContractType for easy selector <-> signature mapping.  Useful for looking up what a selector might be, or if a selector/topic is part of a known contract.  Might follow this up with a command/plugin for tabular display output.
Or at least I knew them as selector/signature, but terminology seems to be different in this source.  I went looking for official defs and they're all over the place as well.  Even the [Solidity ABI spec](https://docs.soliditylang.org/en/develop/abi-spec.html#events) interchanges Method ID and selector.  I did my best to stick within the convention but my naming is probably off.
I often find myself in a situation where I have an event topic or function or error selector that I'm curious if its a member of one of the contracts in my project.  So it …
> feat: adds identifier_definitions and identifier_lookup props to ContractType

- ethpm_types/source.py
- tests/test_source.py
Some people have been complaining about things compiling over and over again...
Well turns out there was bug where the hashes in Ape always registered changes because it is agreed upon to ignore added whitespace at ends of files but that was not happening.
Ignore empty lines in `Source`
* Make a Vyper file in Ape
* Add newlines at the end (more than 1)
* Notice it compiles indefinitely
> fix: issue with content trailing empty lines

- ethpm_types/source.py
- tests/test_source.py
vyper uses the key of `"optmize"` and solidity uses "optimizer" so need to handle both.
> fix: handle when key name is optimize instead of optimizer in set

- ethpm_types/source.py
- tests/test_source.py
Critical bugfix... causing compilation problems in Ape.
Basically, we were ignoring all non-content props in the Source model.
stop ignoring and start using.
you can now set references on Source (see test)
> fix: bug where could not set `references` Source model

- tests/test_contract_type.py
Just making sure these methods work, step 1 in research to fixing this https://github.com/ApeWorX/ape/issues/1811
> test: show that `get_deployment_bytecode` and alike function

- .github/workflows/commitlint.yaml
- .github/workflows/docs.yaml
- .github/workflows/prtitle.yaml
- .github/workflows/publish.yaml
- .github/workflows/test.yaml
- .pre-commit-config.yaml
- ethpm_types/abi.py
- ethpm_types/source.py
- setup.cfg
- setup.py
- tests/test_package_manifest.py
- tests/test_source.py
There was a bug where if a file was empty,
it would try to use the empty str as a
dict to create the source content, due to an improper
truthy check.
> fix: issue with empty file sources

- .github/workflows/test.yaml
So it goes.
Ref: https://github.com/ApeWorX/ape/pull/2020
> fix(devops): pin macos runners to macos-12

- ethpm_types/abi.py
Prior to this change, any downstream initializations of `ABIType` without specifying `internalType=...` in the constructor would raise the typing issue `E: Missing named argument "internalType" for "ABIType"  [call-arg]`. Changing this to a keyword arg allows mypy to correctly detect that this field is not needed.
No functional change
I was working downstream and monkeypatched this change, and observed that mypy stopped complaining
~~- [ ] New test cases have been added and are passing~~
~~- [ ] Documentation has been updated~~
> fix: allow mypy to detect internalType not required

- tests/test_package_manifest.py
little pr... was part of some debugging im doing...
* handle else case first to invert the `not` (less words
* de-indent with an early return so most of the code in the test is 1 less tab indented
> refactor: examples test

- .github/workflows/test.yaml
- ethpm_types/source.py
Enables windows CI tests, uses base path type instead of posix
fixes: #
enabled windows CI test
we'll see!
> feat: windows support

- .github/workflows/test.yaml
The linked issue was closed and they claim to have fixed it so giving it a whirl
> test: re-enable `macos-latest` in CI since

- ethpm_types/manifest.py
- tests/test_package_manifest.py
also fixes https://github.com/ApeWorX/ape/issues/2088 in a way (going back to Ape 0.7)
specify encoding in `write_text()`
> fix: specify encoding during `.unpack()`

- ethpm_types/base.py
- tests/test_abi.py
The deprecated `dict()` and `json()` methods did not have any of the default handlings that `model_dump()` and `model_dump_json()` did
probably should have been added when we switched to pydantic v2
fixes: #116
> fix: handle defaults in deprecated pydantic methods

- ethpm_types/contract_type.py
both userdoc and devdoc were missing docs.
I am currently trying to understand how NatSpec turns into these.
> docs: add doc-strings for the doc-fields in `ContractType`

- setup.py
> chore: loosen pin on eth-pydantic-types

- .pre-commit-config.yaml
- ethpm_types/contract_type.py
- ethpm_types/manifest.py
- setup.cfg
- setup.py
- tests/test_abi.py
- tests/test_basemodel.py
I thought I would reproduce https://github.com/ApeWorX/eth-pydantic-types/issues/14 here but it hasn't happened yet.
Also address some pydantic lint items that come up now (in my ape env anyway)
> chore: add missing tests and update pydantic lint items

- ethpm_types/utils.py
- tests/test_abi.py
fixes: #142 
Fixes: APE-1843
I added accommodations for a lone type as an argument in the parsed Event signature
```parse_signature('PairCreated(address indexed token0, address indexed token1, address pair, uint)')```
> fix: allows event signatures with nameless parameters to be parsed

- .pre-commit-config.yaml
- ethpm_types/abi.py
- ethpm_types/ast.py
- ethpm_types/manifest.py
- ethpm_types/source.py
- ethpm_types/sourcemap.py
- ethpm_types/utils.py
- setup.cfg
- setup.py
- tests/test_basemodel.py
Was not working on pydantic 2.10 because of a URL change they made! 😲 
Have to use our own AnyUrl that includes File
> feat: Support pydantic 2.10

- .pre-commit-config.yaml
- README.md
- ethpm_types/utils.py
- tests/test_sourcemap.py
- tests/test_utils.py
Was getting the error `too many values to unpack (expected 2)` if there was a tuple in an event. This should resolve the issue of parsing the `std_sig` into more than 2 values. 
fixes: https://github.com/ApeWorX/silverback/issues/178
> fix: unable to parse events from signatures when inputs included tuple types

- ethpm_types/abi.py
- tests/test_abi.py
sorry, I missed this when copying over the functionality and I forgot this was a thing you could do when searching logs.
but adds back in passing in lists for single values to have a wider search
also adds in some tests for dynamic values since that was missing
also fixes an issue when passing in wildcards (None) values
also removes the trailing ones like core ape did
> fix: was unable to generate topics when passing a list of values for a singular type

- ethpm_types/abi.py
- tests/test_abi.py
Didn't notice this in any core test but in my ape-boa, it came up, and I thought there was no reason not to allow this, so this fixes it.
detect when is not given a str for string type and hex it
> fix: could not pass bytes for string when encoding topic

- ethpm_types/abi.py
- pyproject.toml
- tests/test_abi.py
Helps fix https://github.com/ApeWorX/ape/issues/2566
~~- [ ] Documentation has been updated~~
> feat(abi): add `__hash__` to BaseABI, to support set operations

- ethpm_types/abi.py
- ethpm_types/contract_type.py
- setup.py
Uses the new names of classes after eth_pydantic_types overhaul
fixes: #
in coordination with: https://github.com/ApeWorX/eth-pydantic-types/pull/11
> feat: upgrade `eth-pydantic-types`
