ApeWorX/ethpm-types

ethpm_types/__init__.py

imported modules to top level
Related issue: #

refactor: imports to top level

---

.github/PULL_REQUEST_TEMPLATE.md
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
pyproject.toml
setup.py

Updated ReadMe and Contributing guides with beta language and fixed `ethpm-types` naming along with small language updates.
Related issue: #

refactor: beta updates

---

ethpm_types/contract_type.py

fix: need type for an empty ABI

---

ethpm_types/abi.py
tests/test_examples.py

fixes: #14 
Copied  `fallback` but made it `payable` and changed the signature

fix: support receive ABI type

---

README.md
setup.py

Release the production version of `ethpm-types`.

chore: production version release

---

ethpm_types/abi.py

Added the `"error"` ABI type support
fixes: #22

feat: add error abi support

---

ethpm_types/source.py

Add imports list to source object. Imports list represents other source objects imported by the source.
fixes: #

feat: add imports list to source

---

docs/index.md

docs: fix index title

---

ethpm_types/abi.py
tests/test_abi.py

feat: add selector to constructor ABI

---

ethpm_types/ast.py

fix: docstr [APE-686]

---

ethpm_types/ast.py

fix: rename to `Function` [APE-757]

---

ethpm_types/ast.py

* repr
* str
* iter nodes (note: cant use `__iter__` because of pydantic)
these just make debugging stuff easier, nothing is required downstream.

feat: AST class improvements [APE-805]

---

.github/workflows/commitlint.yaml
.github/workflows/docs.yaml
.github/workflows/prtitle.yaml
.github/workflows/publish.yaml
.github/workflows/test.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
README.md
pyproject.toml
setup.py

feat: python 3.11 support [APE-902]

---

ethpm_types/contract_type.py
tests/test_cairo.py
tests/test_contract_type.py

we have em for all the other ones so just adding this one too

feat: structs list on contract type [APE-1155]

---

.github/workflows/draft.yaml
.pre-commit-config.yaml
CONTRIBUTING.md
ethpm_types/abi.py
ethpm_types/manifest.py
setup.py
tests/test_abi.py
tests/test_contract_type.py
tests/test_package_manifest.py

some fixes for the schema ouput

fix: improve the schema output [APE-1527]

---

ethpm_types/contract_type.py
tests/test_contract_type.py
tests/test_hexbytes.py
tests/test_package_manifest.py

feat: output method IDs [APE-1541]

---

ethpm_types/base.py
ethpm_types/contract_type.py
ethpm_types/utils.py

fix: rest of method Id fix and other stuff [APE-1542]

---

ethpm_types/manifest.py
tests/test_package_manifest.py

fix: PackageNameError type name fix [APE-1597]

---

ethpm_types/contract_type.py
ethpm_types/manifest.py
ethpm_types/source.py
tests/test_source.py

chore: missed pydantic updates in tests [APE-1611]

---

ethpm_types/contract_type.py

Cleanup from PR #106.  Removed unnecessary assert.
Fixed function arg type.

fix: remove unnecessary assert

---

ethpm_types/manifest.py

I noticed some issues with Annotated so am replacing it for the custom type.
Namely, I realized setting `__name__` on an Annotated type was really really bad and we were doing that here and I can't remember so rather than undo and break it, replacing it this approach maintains the behaviors and doesn't have all the bad things.
some way we do any custom pydantic type; using their weird hooks
tests still pass

fix: replace Annotated with custom type for PackageName

---

.github/workflows/test.yaml
README.md
pyproject.toml
setup.py

feat: add python 3.12 support

---

.github/workflows/docs.yaml

chore: update permissions to add write

---

ethpm_types/abi.py
ethpm_types/utils.py
tests/test_abi.py

Adds `from_signature()` method to `EventABI` and `MethodABI`

feat: adds EventABI.from_signature() and MethodABI.from_signature()

---

.pre-commit-config.yaml
ethpm_types/contract_type.py
setup.py
tests/test_abi.py

feat: add `get` method to ABIList

---

README.md

fixes: #131 
~~- [ ] New test cases have been added and are passing~~

docs: added documentation on how to use from_signature method

---

ethpm_types/source.py
tests/test_source.py

fixes: https://github.com/ApeWorX/ape/issues/2304

fix: issue with `_root` in content-str

---

ethpm_types/abi.py
setup.py
tests/test_abi.py

`topics` did not work when given int
handle the right kwarg based in the type of the input

fix: `topics` issue with encoded topics

---

.github/workflows/test.yaml
.pre-commit-config.yaml
docs/conf.py
ethpm_types/abi.py
ethpm_types/contract_type.py
ethpm_types/manifest.py
ethpm_types/source.py
ethpm_types/sourcemap.py
ethpm_types/utils.py
pyproject.toml
setup.py
tests/test_abi.py
tests/test_basemodel.py
tests/test_cairo.py
tests/test_contract_type.py
tests/test_package_manifest.py
tests/test_source.py
tests/test_utils.py

fixes: #146 
also switches lint to ruff

fix: allow snake_case for `internal_type` on `ABIType` init
